### ISSUE TITLE
CentOS 7 HAWQ binaries require sudo

### ISSUE THREAD

**Issue by josiah14** [wangzw/hawq-devel-env#11]
Requiring sudo makes it difficult to incorporate the greenplum_path.sh script to set the necessary environment variables.  These restrictions also make it difficult for the HAWQ application to read some of the config files.

A suggested correction would be to configure HAWQ to run from a hawqadmin user that would need to be created, and give that user access to the configuration files.

**Comment by josiah14** [comment]
Here is a PR which outlines a working build process I was able to figure out in the couple of hours I had.

https://github.com/wangzw/hawq-devel-env/pull/9

**Comment by wangzw** [comment]
merged
