### ISSUE TITLE
Incorporate current build steps into the Dockerfile

### ISSUE THREAD

**Issue by josiah14** [wangzw/hawq-devel-env#12]
Ideally, someone should only need to `docker pull` the datanode container and the namenode container and then use docker-compose to run them together.  No executing additional build steps inside of the Docker Containers should be necessary for the end user - that should be incorporated into the Dockerfile so that everything is ready to go for the developer who just wants to download HAWQ and start tinkering with it.

**Comment by wangzw** [comment]
Yes. But downloading docker images is very slow in China or even cannot complete. So I have to build the images locally.

docker-compose cannot work well when I create this project. It get improved right now. So it is better to use docker-compose now instead of complex scripts.
