### ISSUE TITLE
datanode start failed when run "make run"  on debian

### ISSUE THREAD

**Issue by taojin0505** [wangzw/hawq-devel-env#4]
hadoop@jin:~/hawq-devel-env/centos7-docker$ make run
make[1]: Entering directory '/home/hadoop/hawq-devel-env/centos7-docker'
create centos7-data container
centos7-data container already exist!
make[1]: Leaving directory '/home/hadoop/hawq-devel-env/centos7-docker'
make[1]: Entering directory '/home/hadoop/hawq-devel-env/centos7-docker'
make[2]: Entering directory '/home/hadoop/hawq-devel-env/centos7-docker'
run centos7-namenode container
centos7-namenode container already exist!
make[2]: Leaving directory '/home/hadoop/hawq-devel-env/centos7-docker'
/bin/sh: 1: Syntax error: Bad for loop variable
/home/hadoop/hawq-devel-env/centos7-docker/Makefile:69: recipe for target 'run-hdfs' failed
make[1]: **\* [run-hdfs] Error 2
make[1]: Leaving directory '/home/hadoop/hawq-devel-env/centos7-docker'
Makefile:56: recipe for target 'run' failed
make: **\* [run] Error 2
hadoop@jin:~/hawq-devel-env/centos7-docker$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                CREATED              STATUS              PORTS               NAMES
d64266cee8b8        mayjojo/hawq-test:centos7    "entrypoint.sh bash"   About a minute ago   Up About a minute                       centos7-namenode
b5b27c2c551d        mayjojo/hawq-devel:centos7   "/bin/true"            18 minutes ago       Created                                 centos7-data

SOLVED by set the default shell to bash instead of dash.
$sudo dpkg-reconfigure dash
then select NO.

**Comment by wangzw** [comment]
The scripts suppose to work with bash, do you have any idea about make it work with both bash and dash? Would you please file a pull request to fix this issue?

**Comment by taojin0505** [comment]
OK,I'll fix it in dash in the next few days

**Comment by wangzw** [comment]
Merged. Thanks for your contribution.
