### ISSUE TITLE
could not recreate the data container after remove it

### ISSUE THREAD

**Issue by taojin0505** [wangzw/hawq-devel-env#6]
it was a logic bug.
After remove the data container,run "make create-date-container" could not create the data container.

this bug was caused by checking data-container in the code line 45,
        @if [ -z "`docker ps -a --filter="name=${CLUSTER_ID}-data" | grep -v CONTAINER`" ]; then \
because there are container like "centos-datanode1",so docker ps -a --filter="name=${CLUSTER_ID}-data$$" could not return a null string.

I changee this command to
 docker ps -a --filter="name=${CLUSTER_ID}-data$$" 
fixed this issue.

**Comment by wangzw** [comment]
nice catch
